export const departments = [
    {name: "Direção Geral", sigla: "DG"},
    {name: "Gabinete do Diretor", sigla: "GAB"},
    {name: "Recepção"},
    {name: "Núcleo de Apoio á Gestão de Pessoas", sigla: "NAGP"},
    {name: "Núcleo de Comunicação e Eventos", sigla: "NCE"},
    {name: "Núcleo de Gestão da Tecnologia da Informação", sigla: "NGTI"},
    {name: "Diretoria Administrativa", sigla: "DADM"},
    {name: "Coordenação Financeira Contábi , ", sigla: "CFC"},
    {name: "Núcleo de Execução Orçamentária e Financeira", sigla: "NEOF"},
    {name: "Núcleo de Licitação", sigla: "NL"},
    {name: "Núcleo de Contratos", sigla: "NC"},
    {name: "Setor de Almoxarifado", sigla: "STA"},
    {name: "Setor de Patrimônio", sigla: "STP"},
    {name: "Coordenação de Suprimentos e Logística", sigla: "CSL"},
    {name: "Setor de Oficina", sigla: "STO"},
    {name: "Diretoria Acadêmica", sigla: "DA"},
    {name: "Coordenação de Ensino", sigla: "CE"},
    {name: "Coordenações dos Cursos Superiores: Geografia, Ciências Biológicas, Zootecnia"},
    {name: "Núcleo de Apoio ao Processo de ensino Aprendizagem Permanecia e Êxito do Educando", sigla: "NAPEA"},
    {name: "Cursos de Graduação (Módulo Novo)"},
    {name: "Coordenação de Pesquisa", sigla: "CP"},
    {name: "Coordenação de Extensão"},
    {name: "Sala de Audiovisual"},
    {name: "Coordenações dos Cursos Técnicos Integrados ao Ensino Médio: Agropecuária, Alimentos, Zootecnia, PROEJA"},
    {name: "Núcleo de Apoio ao Processo de Ensino–Aprendizagem, Permanência e Êxito do Educando"},
    {name: "Coordenação Pedagógica"},
    {name: "Setor de Biblioteca", sigla: "STB"},
    {name: "Setor de Biblioteca (Acervo)", sigla: "STB"},
    {name: "Coordenação de Relações Institucionais", sigla: "NRI"},
    {name: "Coordenação de Estágio"},
    {name: "Sala dos professores"},
    {name: "Sala de reuniões"},
    {name: "Ramal Corredor da Administração"},
    {name: "Secretaria de Registros Acadêmicos", sigla: "SRA"},
    {name: "Coordenação de Assuntos Estudantis", sigla: "CAE"},
    {name: "Núcleo de Apoio Pedagógico e Psicossocial", sigla: "NAPSI"},
    {name: "Coordenação de Nutrição e Sáude (Sala de Enfermagem)", sigla: "NNS"},
    {name: "Coordenação de Nutrição e Sáude (Refeitório)", sigla: "NNS"},
    {name: "Coordenação de Nutrição e Sáude (Consultório Odontológico)", sigla: "NNS"},
    {name: "Núcleo de Atendimento às Pessoas com Necessidades Específicas", sigla: "NAPNE"},
    {name: "Coordenação de Unidade Educativa de Campo", sigla: "CUEC"},
    {name: "Horta"},
    {name: "Bovinocultura"},
    {name: "Caprinocultura"},
    {name: "Suinocultura"},
    {name: "Pavilhão Agroindustria"},
    {name: "Laboratório de Biologia"},
    {name: "Laboratório de Química"},
    {name: "Laboratório de Informática"},
    {name: "Laboratório de Informática 2"},
    {name: "Portaria – Vigilantes de Plantão"},
    {name: "Portaria (1º Andar) –  Vigilantes de Plantão"},
    {name: "Sala da Vigilância (Alojamento Feminino) – Vigilantes de Plantão"},
    {name: "Sala do preposto da GR3"},
    {name: "Sala do preposto da Atitude"},
    {name: "Recepção (ramal 2)"},
    {name: "Diretoria Administrativa (ramal 2)", sigla: "DADM"},
    {name: "Setor de Oficina (ramal 2)", sigla: "STO"},
    {name: "Secretaria de Registros Acadêmicos (ramal 2)", sigla: "SRA"},
    {name: "Coordenação de Assuntos Estudantis (ramal 2)", sigla: "CAE"},
]