
export const ramais = [
    {
        numero: 40,
    }, {
        numero: 48,
    }, {
        numero: 11,
    }, {
        numero: 9,
    }, {
        numero: 13,
    }, {
        numero: 106,
    }, {
        numero: 32,
    }, {
        numero: 31,
    }, {
        numero: 73,
    }, {
        numero: 57,
    }, {
        numero: 43,
    }, {
        numero: 105,
    }, {
        numero: 18,
    }, {
        numero: 20,
    }, {
        numero: 39,
    }, {
        numero: 72,
    }, {
        numero: 15,
    }, {
        numero: 25,
    }, {
        numero: 65,
    }, {
        numero: 49,
    }, {
        numero: 27,
    }, {
        numero: 98,
    }, {
        numero: 41,
    }, {
        numero: 34,
    }, {
        numero: 58,
    }, {
        numero: 66,
    }, {
        numero: 22,
    }, {
        numero: 81,
    }, {
        numero: 19,
    }, {
        numero: 107,
    }, {
        numero: 17,
    }, {
        numero: 71,
    }, {
        numero: 109,
    }, {
        numero: 28,
    }, {
        numero: 111,
    }, {
        numero: 36,
    },{
        numero: 42,
    }, {
        numero: 77,
    }, {
        numero: 68,
    }, {
        numero: 52,
    }, {
        numero: 75,
    }, {
        numero: 55,
    }, {
        numero: 62,
    }, {
        numero: 61,
    }, {
        numero: 23,
    }, {
        numero: 12,
    }, {
        numero: 45,
    }, {
        numero: 46,
    }, {
        numero: 67,
    }, {
        numero: 74,
    }
]